name = "agenda-iprevenir"
compatibility_date = "2025-04-12"

# Configuração para Cloudflare Pages
[site]
bucket = "./dist"

# Diretório de saída para Cloudflare Pages
pages_build_output_dir = "dist"

# Configuração para Pages Functions
[build]
command = "npm run build"

[functions]
directory = "./functions"
