name = "agenda-iprevenir"
type = "javascript"
compatibility_date = "2025-04-12"

# Configuração para sites estáticos
[site]
bucket = "./dist"

# Configuração para Workers Sites
[build]
command = "npm run build"
[build.upload]
format = "service-worker"
